### ISSUE TITLE
Preprocessor - 1: Untar Files

### ISSUE THREAD

**Issue by v2thegreat** [Social-Media-Public-Analysis/Social-Media-Public-Analysis#24]
As files are downloaded:
- [x] untar/unzip files
- [x] delete the tar file
- [x] leave them as compressed files (*.json.bz2)

**Comment by erb13020** [comment]
- [x] Files can be untared

- [ ] delete the tar file

- [ ] leave them as compressed files

We can untar one file at a time. Untaring needs to be speed up. We also should find a way to untar multiple files at a time to speed up things even more.

**Comment by v2thegreat** [comment]
Based on the call on Monday 21st Sept, we discussed on how multiple files is going to be slow since you were testing on an HDD, and even with the bash command `tar -xvf`, it was slow. Because of that, we're going to be skipping multithreading the untaring process
